### ISSUE TITLE
باگ فیلدهای پسورد صفحه عضویت

### ISSUE THREAD

**Issue by parissashahabi** [parissashahabi/heifes#11]
برای فیلدهای رمز عبور و تکرار رمز عبور state های جداگانه با اسم مرتبط به خود تعریف بشه.
الان وقتی آیکون Show Password برای یکی از فیلدها زده شده جفت فیلدها visibilityش تغییر میکنه!

**Comment by nafis-momeni** [comment]
ببخشید دیگه تکرار نمیشه :)
